### ISSUE TITLE
How to use in check_mk ?

### ISSUE THREAD

**Issue by rolandsteinmeyer** [superdachs/check_tp-link_easysmart#1]
Can you give a short description on how to use this in check_mk (best practise) ? Where do the files go ? Since there is no cmk agent on the switch itself and no snmp, the plugin needs to be executed on the cmk server, right ? Do I need a "classical Monitoring checks" rule ? Is inventory possible somehow ?

**Comment by rolandsteinmeyer** [comment]
Found it myself. 
easysmart goes to site directory ~/local/share/check_mk/checks
easysmart_datasource.py needs to be run as Datasource program as described in https://checkmk.de/cms_datasource_programs.html .

**Comment by simatec** [comment]
I have a question about the integration in CheckMK 2.0.

Where can I transfer the user data such as username and password as well as the host name?

I can't find a way to configure this. When I enter the Userdata in easysmart.py, the call runs.

But you can safely configure it in Checkmk, right?

**Comment by simatec** [comment]
I hand over with the following command:

`easysmart.py -H $HOSTADDRESS$ -U $ARG1$ -P $ARG2$ -M errors -p 1,3,5 -w 10 -c 15 --html`

How can I pass $ARG1$ and $ARG2$ or $HOSTNAME$?
